version: "3.8"
services:
  backend:
    image: express-image:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: always

  frontend:
    image: react-image:latest
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend
    restart: always

networks:
  mynetwork:
    name: DestinationMesh
    driver: bridge
